# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v0.20240712.1-2-geb68385
_src_path: gh:level12/copier-py-package
author_email: randy@syrings.us
author_name: Randy Syring
project_name: WikiSyncGHAction
py_module: wikisyncghaction
python_version: '3.12'
script_name: wikisyncghaction
use_pipx: false
virtualenv_name: wikisyncghaction
