version: 2.1

orbs:
  # https://circleci.com/developer/orbs/orb/codecov/codecov
  codecov: codecov/codecov@4.1.0

jobs:

  nox:

    docker:
      - image: cimg/python:3.12

    steps:
      - checkout

      - run:
          name: run nox
          command: |
            mise run ci-nox

      - store_test_results:
          path: ci/test-reports/

      - codecov/upload


workflows:
  main:
    jobs:
      - nox
