#!/usr/bin/env python
from os import environ
from pathlib import Path
from sync_utils import sub_run
import sys

proj_root = Path(environ['MISE_PROJECT_ROOT'])

env = environ | {
'GITHUB_WORKSPACE': str(proj_root),
'GITHUB_REPOSITORY': 'level12/gh-action-wiki-sync',
'INPUT_DOCS_PATH': 'wiki',
'INPUT_RUN_SYNC': environ.get('INPUT_RUN_SYNC', 'false'),
'GITHUB_EVENT_NAME': 'push',
}

result = sub_run(proj_root / 'wiki-sync.py', *sys.argv[1:], env=env, check=False)
sys.exit(result.returncode)
