name: Docs <-> Wiki

on:
  push:
    paths:
      - "wiki/**"
      - ".github/workflows/**"
      - "src/**"
      - "action.yaml"
  # gollum is the wiki add/update event and this only triggers for the default branch.  I.e. if
  # an update is made to the wiki, only the master branch will be updated.
  gollum:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  sync-docs:
    if: github.event_name != 'gollum' || !contains(github.event.pages[0].summary, 'wiki sync bot:')
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      # - name: Dump GitHub context
      #   env:
      #     GITHUB_CONTEXT: ${{ toJson(github) }}
      #   run: echo "$GITHUB_CONTEXT"

      - name: GitHub Wiki Sync
        uses: level12/gh-action-wiki-sync@main
        with:
          github_token: ${{ github.token }}
